version: '3'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      # - 3000:3000/tcp
      # - 80:80/tcp
      # - 443:443/tcp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - traefik_default
    labels:
      traefik.http.services.adguard.loadbalancer.server.port: "3000"
      traefik.http.routers.adguard.rule: "Host(`adguard.${MY_DOMAIN}`)"
      traefik.http.routers.adguard.entrypoints: "websecure"
      traefik.http.routers.adguard.tls: "true"
      traefik.http.routers.adguard.tls.certresolver: "letsencrypt"
      traefik.http.routers.adguard.tls.domains[0].main: "adguard.${MY_DOMAIN}"
      traefik.docker.network: "traefik_default"
      traefik.enable: "true"

volumes:
  work:
  conf:    

networks:
  traefik_default:
    external: 
      name: traefik_default  

