version: '2'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    network_mode: host

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
      - HOSTNAME="PlexServer"

    volumes:
      - config:/config
      - transcode:/transcode
      - bananas_downloads:/media/downloads
      - bananas_video:/media/video

volumes:
  config:
  transcode:
  bananas_downloads:
    external: true
  bananas_video:
    external: true