version: '3.7'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
      - HOSTNAME="PlexServer"

    volumes:
      - config:/config
      - transcode:/transcode
      - bananas_downloads:/media/downloads

volumes:
  config:
  transcode:
  bananas_downloads:
    external: true