version: '3'
services:
  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: keycloak
    restart: "unless-stopped"
    volumes:
      - theme:/opt/jboss/keycloak/themes/tews
      - data:/opt/jboss/keycloak/standalone/data
    networks:
      - traefik_default
    environment:
      TZ: "Europe/Paris"
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: h2
      KEYCLOAK_USER: ${ADMIN_USER}
      KEYCLOAK_PASSWORD: ${ADMIN_PASSWORD}
    labels:
      traefik.http.routers.keycloak.rule: "Host(`auth.${MY_DOMAIN}`)"
      traefik.http.services.keycloak.loadbalancer.server.port: "8080"
      # traefik.http.routers.keycloak.entrypoints: "web"
      traefik.http.routers.keycloak.entrypoints: "websecure"
      traefik.http.routers.keycloak.tls: "true"
      traefik.http.routers.keycloak.tls.certresolver: "letsencrypt"
      traefik.http.routers.keycloak.tls.domains[0].main: "auth.${MY_DOMAIN}"
      traefik.docker.network: "traefik_default"
      traefik.enable: "true"
    user: 1000:1000

volumes:
  theme:
  data:

networks:
  traefik_default:
    external: 
      name: traefik_default