version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn:5.0
  container_name: transmission
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  ports:
    - "9091:9091"
    - "8888:8888"
#  dns:
#    - 8.8.8.8
#    - 8.8.4.4
  volumes:
    - config:/config
    - data:/data
    - downloads:/data/completed
  environment:
    - PUID=1028
    - PGID=100
    - OPENVPN_PROVIDER=${VPN_PROVIDER}
    - OPENVPN_USERNAME=${VPN_USER}
    - OPENVPN_PASSWORD=${VPN_PASSWORD}
    - OPENVPN_CONFIG=${VPN_CONFIG}
    - OPENVPN_OPTS=--verb 4
    - LOCAL_NETWORK=192.168.2.0/24,192.168.0.0/24
    - TRANSMISSION_RATIO_LIMIT=1
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - TRANSMISSION_WATCH_DIR=/data/watch
    - TRANSMISSION_WATCH_DIR_ENABLED=true
    - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
    - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
    - TRANSMISSION_DOWNLOAD_DIR=/data/completed/incoming
    - TRANSMISSION_SPEED_LIMIT_UP=25
    - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
    - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
    - TRANSMISSION_START_ADDED_TORRENTS=true
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
  networks:
    - homelab
  restart: unless-stopped

volumes:
  config:
  data:
  downloads:
    external: true

networks:
  homelab:
    external: true
    name: homelab


